Base name = 20230416_11_13_58_Cage4278767_Animal02_STRAINFOSTRAPXAI9TDTOMATO_Male_Cohort4_BEHAVIORTMTWATERCONTROL
Looking for images in /athena/listonlab/scratch/dje4001/lightsheet_scratch/WATERCONTROL/lightsheet/raw/20230416_11_13_58_Cage4278767_Animal02_STRAINFOSTRAPXAI9TDTOMATO_Male_Cohort4_BEHAVIORTMTWATERCONTROL...
Found 124656 compatible images
Setting up 112 workers...
Pystripe batch processing progress:
  0%|          | 0/124656 [00:00<?, ?it/s]  0%|          | 1/124656 [03:40<7645:06:41, 220.79s/it]  0%|          | 3/124656 [03:46<2059:41:11, 59.48s/it]   0%|          | 4/124656 [03:54<1443:39:56, 41.69s/it]  0%|          | 6/124656 [03:55<732:14:53, 21.15s/it]   0%|          | 8/124656 [03:56<437:02:15, 12.62s/it]  0%|          | 9/124656 [03:58<353:42:13, 10.22s/it]  0%|          | 12/124656 [03:59<180:00:05,  5.20s/it]  0%|          | 15/124656 [04:02<119:38:30,  3.46s/it]  0%|          | 34/124656 [04:02<26:15:32,  1.32it/s]   0%|          | 34/124656 [04:20<26:15:32,  1.32it/s]  0%|          | 621/124656 [54:04<1430:37:11, 41.52s/it]  0%|          | 113/124656 [07:38<82:23:56,  2.38s/it]  0%|          | 114/124656 [07:49<86:50:25,  2.51s/it]  0%|          | 115/124656 [07:55<89:36:59,  2.59s/it]  0%|          | 117/124656 [07:58<86:54:28,  2.51s/it]  0%|          | 121/124656 [08:02<79:40:59,  2.30s/it]  0%|          | 136/124656 [08:04<47:40:44,  1.38s/it]  0%|          | 139/124656 [08:07<46:14:04,  1.34s/it]  0%|          | 140/124656 [08:09<48:16:10,  1.40s/it]  0%|          | 142/124656 [08:11<47:22:47,  1.37s/it]  0%|          | 145/124656 [08:17<51:01:57,  1.48s/it]  0%|          | 152/124656 [08:23<41:10:21,  1.19s/it]  0%|          | 199/124656 [08:27<10:56:16,  3.16it/s]  0%|          | 225/124656 [10:03<56:01:00,  1.62s/it]  0%|          | 226/124656 [10:04<55:58:58,  1.62s/it]  0%|          | 227/124656 [10:18<67:24:00,  1.95s/it]  0%|          | 228/124656 [10:18<65:24:24,  1.89s/it]  0%|          | 229/124656 [10:30<84:05:49,  2.43s/it]  0%|          | 232/124656 [10:38<84:48:12,  2.45s/it]  0%|          | 236/124656 [10:43<74:27:29,  2.15s/it]  0%|          | 239/124656 [10:44<61:20:10,  1.77s/it]  0%|          | 240/124656 [10:44<56:16:06,  1.63s/it]  0%|          | 243/124656 [10:51<61:22:46,  1.78s/it]  0%|          | 254/124656 [11:13<66:45:04,  1.93s/it]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 652, in _read_filter_save
    read_filter_save(**input_dict)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 607, in read_filter_save
    fimg = filter_streaks(img, sigma, level=level, wavelet=wavelet, crossover=crossover, threshold=threshold, flat=flat, dark=dark)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 471, in filter_streaks
    foreground_filtered = filter_subband(foreground, sigma[0], level, wavelet)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 407, in filter_subband
    img_log_filtered = waverec(coeffs_filt, wavelet)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 212, in waverec
    return pywt.waverec2(coeffs, wavelet, mode='symmetric', axes=(-2, -1))
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pywt/_multilevel.py", line 335, in waverec2
    a = idwt2((a[idxs], d), wavelet, mode, axes)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pywt/_multidim.py", line 118, in idwt2
    return idwtn(coeffs, wavelet, mode, axes)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pywt/_multidim.py", line 308, in idwtn
    new_coeffs[key] = idwt_axis(L, H, wav, mode, axis)
  File "pywt/_extensions/_dwt.pyx", line 239, in pywt._extensions._dwt.idwt_axis
  File "pywt/_extensions/_dwt.pyx", line 285, in pywt._extensions._dwt.idwt_axis
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 12.2 MiB for an array with shape (802, 2000) and data type float64
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fs01/dje4001/anaconda3/bin/pystripe", line 8, in <module>
    sys.exit(main())
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 972, in main
    batch_filter(input_path,
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 824, in batch_filter
    list(tqdm.tqdm(pool.imap(_read_filter_save, args, chunksize=chunks), total=len(args), ascii=True))
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 652, in _read_filter_save
    read_filter_save(**input_dict)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 607, in read_filter_save
    fimg = filter_streaks(img, sigma, level=level, wavelet=wavelet, crossover=crossover, threshold=threshold, flat=flat, dark=dark)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 471, in filter_streaks
    foreground_filtered = filter_subband(foreground, sigma[0], level, wavelet)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 407, in filter_subband
    img_log_filtered = waverec(coeffs_filt, wavelet)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 212, in waverec
    return pywt.waverec2(coeffs, wavelet, mode='symmetric', axes=(-2, -1))
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pywt/_multilevel.py", line 335, in waverec2
    a = idwt2((a[idxs], d), wavelet, mode, axes)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pywt/_multidim.py", line 118, in idwt2
    return idwtn(coeffs, wavelet, mode, axes)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pywt/_multidim.py", line 308, in idwtn
    new_coeffs[key] = idwt_axis(L, H, wav, mode, axis)
  File "pywt/_extensions/_dwt.pyx", line 239, in pywt._extensions._dwt.idwt_axis
  File "pywt/_extensions/_dwt.pyx", line 285, in pywt._extensions._dwt.idwt_axis
numpy.core._exceptions.MemoryError: Unable to allocate 12.2 MiB for an array with shape (802, 2000) and data type float64
