Base name = 20230416_13_35_15_Cage4278725_Animal03_STRAINFOSTRAPXAI9TDTOMATO_Female_Cohort4_BEHAVIORTMTWATERCONTROL
Looking for images in /athena/listonlab/scratch/dje4001/lightsheet_scratch/WATERCONTROL/lightsheet/raw/20230416_13_35_15_Cage4278725_Animal03_STRAINFOSTRAPXAI9TDTOMATO_Female_Cohort4_BEHAVIORTMTWATERCONTROL...
Found 133252 compatible images
Setting up 112 workers...
Pystripe batch processing progress:
  0%|          | 0/133252 [00:00<?, ?it/s]  0%|          | 1/133252 [03:01<6699:56:46, 181.01s/it]  0%|          | 13/133252 [03:08<391:11:31, 10.57s/it]   0%|          | 113/133252 [05:16<75:31:51,  2.04s/it]  0%|          | 114/133252 [05:21<76:33:25,  2.07s/it]  0%|          | 123/133252 [05:25<68:14:43,  1.85s/it]  0%|          | 144/133252 [05:31<49:36:03,  1.34s/it]  0%|          | 154/133252 [05:32<41:36:53,  1.13s/it]  0%|          | 157/133252 [05:34<40:10:03,  1.09s/it]  0%|          | 158/133252 [05:38<43:00:29,  1.16s/it]  0%|          | 160/133252 [05:44<49:08:55,  1.33s/it]  0%|          | 179/133252 [05:48<27:06:52,  1.36it/s]  0%|          | 195/133252 [05:49<16:59:32,  2.18it/s]  0%|          | 215/133252 [05:50<11:16:00,  3.28it/s]  0%|          | 215/133252 [06:10<11:16:00,  3.28it/s]  0%|          | 225/133252 [07:49<108:23:38,  2.93s/it]  0%|          | 226/133252 [08:08<127:01:20,  3.44s/it]  0%|          | 232/133252 [08:09<101:31:25,  2.75s/it]  0%|          | 246/133252 [08:10<60:02:41,  1.63s/it]   0%|          | 250/133252 [08:13<55:29:43,  1.50s/it]  0%|          | 258/133252 [08:13<39:59:36,  1.08s/it]  0%|          | 268/133252 [08:14<26:49:50,  1.38it/s]  0%|          | 270/133252 [08:17<29:35:06,  1.25it/s]  0%|          | 272/133252 [08:19<31:12:09,  1.18it/s]  0%|          | 274/133252 [08:20<29:03:08,  1.27it/s]  0%|          | 276/133252 [08:24<36:13:10,  1.02it/s]  0%|          | 277/133252 [08:29<52:50:42,  1.43s/it]  0%|          | 287/133252 [08:30<24:04:17,  1.53it/s]  0%|          | 290/133252 [08:33<26:17:04,  1.41it/s]  0%|          | 302/133252 [08:35<14:56:36,  2.47it/s]  0%|          | 314/133252 [08:36<9:27:55,  3.90it/s]   0%|          | 315/133252 [08:38<12:07:30,  3.05it/s]  0%|          | 319/133252 [08:42<19:12:48,  1.92it/s]  0%|          | 337/133252 [10:27<134:15:11,  3.64s/it]  0%|          | 338/133252 [10:35<140:07:49,  3.80s/it]  0%|          | 339/133252 [10:46<155:36:25,  4.21s/it]  0%|          | 345/133252 [10:49<109:22:43,  2.96s/it]3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 652, in _read_filter_save
    read_filter_save(**input_dict)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 607, in read_filter_save
    fimg = filter_streaks(img, sigma, level=level, wavelet=wavelet, crossover=crossover, threshold=threshold, flat=flat, dark=dark)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 471, in filter_streaks
    foreground_filtered = filter_subband(foreground, sigma[0], level, wavelet)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 388, in filter_subband
    img_log = np.log(1 + img)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 24.4 MiB for an array with shape (1600, 2000) and data type float64
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fs01/dje4001/anaconda3/bin/pystripe", line 8, in <module>
    sys.exit(main())
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 972, in main
    batch_filter(input_path,
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 824, in batch_filter
    list(tqdm.tqdm(pool.imap(_read_filter_save, args, chunksize=chunks), total=len(args), ascii=True))
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 652, in _read_filter_save
    read_filter_save(**input_dict)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 607, in read_filter_save
    fimg = filter_streaks(img, sigma, level=level, wavelet=wavelet, crossover=crossover, threshold=threshold, flat=flat, dark=dark)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 471, in filter_streaks
    foreground_filtered = filter_subband(foreground, sigma[0], level, wavelet)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 388, in filter_subband
    img_log = np.log(1 + img)
numpy.core._exceptions.MemoryError: Unable to allocate 24.4 MiB for an array with shape (1600, 2000) and data type float64
